name: cdk release code

on:
  workflow_call:
    inputs:
      pinned_image:
        type: string
        required: true
      stack_name:
        required: true
        type: string
      target_environment:
        required: true
        type: string
      version:
        required: true
        type: string
      commit_id:
        required: true
        type: string
      is_pull_request:
        required: true
        type: boolean
    secrets:
      CLOUD_FORMATION_DEPLOY_ROLE:
        required: true

permissions: {}

jobs:
  deploy_cdk_code:
    runs-on: ubuntu-22.04
    container:
      image: ${{ inputs.pinned_image }}
      options: --user 1001:1001 --group-add 128
    defaults:
      run:
        shell: bash
    name: "Deploy cdk app StorageResourcesApp stack storage-resources"
    environment: ${{ inputs.target_environment }}
    permissions:
      id-token: write
      contents: write
    env:
      AWS_MAX_RETRY: 20
    steps:
      - name: copy .tool-versions
        run: |
          cp /home/vscode/.tool-versions "$HOME/.tool-versions"

      - name: build_artifact download
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: cdk_build_artifact

      - name: extract build_artifact
        run: |
          tar -xf artifact.tar

      - name: Configure AWS Credentials for deploy
        id: connect-aws-deploy
        uses: aws-actions/configure-aws-credentials@ec61189d14ec14c8efccab744f656cffd0e33f37 # v6.1.0
        with:
          aws-region: eu-west-2
          role-to-assume: ${{ secrets.CLOUD_FORMATION_DEPLOY_ROLE }}
          role-session-name: eps-storage-resources-cdk-release
          output-credentials: true

      - name: Fix path
        run: |
          echo "$PWD/node_modules/.bin" >> "$GITHUB_PATH"

      - name: "Run create changeset for cdk app StorageResourcesApp stack ${{ inputs.stack_name }} new tag"
        run: |
          # Changeset name must past this regex: [a-zA-Z][-a-zA-Z0-9]*|arn:[-a-zA-Z0-9:/]*
          # See https://docs.aws.amazon.com/cli/latest/reference/cloudformation/describe-change-set.html
          VERSION_NUMBER_HYTHENATED="${CDK_CONFIG_versionNumber//./-}"

          CDK_CHANGE_SET_NAME="${CDK_CONFIG_stackName}-changeset-${VERSION_NUMBER_HYTHENATED}-$(date +%s)"
          export CDK_CHANGE_SET_NAME
          echo "CDK_CHANGE_SET_NAME=${CDK_CHANGE_SET_NAME}" >> "$GITHUB_ENV"
          echo "Created changeset ${CDK_CHANGE_SET_NAME} for app StorageResourcesApp stack ${CDK_CONFIG_stackName}" >> "$GITHUB_STEP_SUMMARY"
          npm run cdk-prepare-changeset --workspace cdk 2>&1 | tee "cdk_deploy_new_tag.log"
        shell: bash
        env:
          AWS_REGION: "eu-west-2"
          CDK_APP_NAME: "StorageResourcesApp"
          CDK_CONFIG_isPullRequest: ${{ inputs.is_pull_request }}
          CDK_CONFIG_environment: "${{ inputs.target_environment }}"
          CDK_CONFIG_commitId: "${{ inputs.commit_id }}"
          CDK_CONFIG_versionNumber: "${{ inputs.version }}"
          CDK_CONFIG_stackName: "${{ inputs.stack_name }}"
          REQUIRE_APPROVAL: "never"
          
      - name: Execute change set
        run: |
          echo "Executing change set"
          aws cloudformation execute-change-set \
            --stack-name "${STACK_NAME}" \
            --change-set-name "${CDK_CHANGE_SET_NAME}"
        env:
          STACK_NAME: ${{ inputs.stack_name }}

      - name: Wait for change set execution to complete
        run: |
          echo "Waiting for change set execution to complete"
          aws cloudformation wait stack-update-complete \
            --region eu-west-2 \
            --stack-name "${STACK_NAME}"
        env:
          STACK_NAME: ${{ inputs.stack_name }}

      - name: Checkout gh-pages
        if: inputs.is_pull_request == 'false'
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: gh-pages
          path: gh-pages
          persist-credentials: false

      - name: Update release tag in github pages
        if: inputs.is_pull_request == 'false'
        run: |
          cd gh-pages
          NOW=$(date +'%Y-%m-%dT%H:%M:%S')
          echo "tag,release_datetime" > "_data/${TARGET_ENVIRONMENT}_${STACK_NAME}_${AWS_REGION}_latest.csv"
          echo "${VERSION},${NOW}" >> "_data/${TARGET_ENVIRONMENT}_${STACK_NAME}_${AWS_REGION}_latest.csv"
          echo "${VERSION},${NOW}" >> "_data/${TARGET_ENVIRONMENT}_${STACK_NAME}_${AWS_REGION}_deployments.csv"
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add "_data/${TARGET_ENVIRONMENT}_${STACK_NAME}_${AWS_REGION}_latest.csv"
          git add "_data/${TARGET_ENVIRONMENT}_${STACK_NAME}_${AWS_REGION}_deployments.csv"
          git commit -m "update releases for ${TARGET_ENVIRONMENT} and stack ${STACK_NAME}"
          parallel --retries 10 --delay 3 ::: "git pull --rebase && git push"
        env:
          STACK_NAME: ${{ inputs.stack_name }}
          TARGET_ENVIRONMENT: ${{ inputs.target_environment }}
          VERSION: ${{ inputs.version }}
          AWS_REGION: "eu-west-2"
