name: Merge to main

on:
  push:
    branches: [main]

permissions: {}

jobs:
  get_config_values:
    uses: NHSDigital/eps-common-workflows/.github/workflows/get-repo-config.yml@c4efd04c5ff1c7e92e7fe5932b29d0de1a301cdf # v6.0.14
    permissions:
      attestations: read
      contents: read
      packages: read

  quality_checks:
    uses: NHSDigital/eps-common-workflows/.github/workflows/quality-checks-devcontainer.yml@c4efd04c5ff1c7e92e7fe5932b29d0de1a301cdf # v6.0.14
    needs: [get_config_values]
    with:
      pinned_image: ${{ needs.get_config_values.outputs.pinned_image }}
    permissions:
      contents: read
      id-token: write
      packages: read
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  get_commit_id:
    runs-on: ubuntu-22.04
    outputs:
      commit_id: ${{ steps.commit_id.outputs.commit_id }}
    steps:
      - name: Get Commit ID
        id: commit_id
        run: |
          echo "commit_id=${{ github.sha }}" >> "$GITHUB_OUTPUT"

  tag_release:
    needs: [quality_checks, get_commit_id, get_config_values]
    uses: NHSDigital/eps-common-workflows/.github/workflows/tag-release-devcontainer.yml@c4efd04c5ff1c7e92e7fe5932b29d0de1a301cdf # v6.0.14
    permissions:
      contents: write
      id-token: write
      packages: write
    with:
      dry_run: true
      pinned_image: ${{ needs.get_config_values.outputs.pinned_image }}
      branch_name: main
      tag_format: ${{ needs.get_config_values.outputs.tag_format }}

  package_cdk_code:
    needs: [get_config_values]
    uses: ./.github/workflows/cdk_package_code.yml
    permissions:
      contents: read
      packages: read
      id-token: write
    with:
      pinned_image: ${{ needs.get_config_values.outputs.pinned_image }}

  deploy_dev:
    needs: [quality_checks, package_cdk_code, tag_release, get_commit_id, get_config_values]
    uses: ./.github/workflows/cdk_release_code.yml
    permissions:
      contents: write
      id-token: write
    with:
      pinned_image: ${{ needs.get_config_values.outputs.pinned_image }}
      stack_name: storage-resources
      target_environment: dev
      version: ${{ needs.tag_release.outputs.version_tag }}
      commit_id: ${{ needs.get_commit_id.outputs.commit_id }}
      is_pull_request: false
    secrets:
      CLOUD_FORMATION_DEPLOY_ROLE: ${{ secrets.DEV_CLOUD_FORMATION_DEPLOY_ROLE }}
